export const IMAGES = {
    LOAD: 'IMAGES_LOAD',
    LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
    LOAD_FAILURE: 'IMAGES_LOAD_FAILURE',
};

export const STATS = {
    LOAD: 'STATs_LOAD',
    LOAD_SUCCESS: 'STATs_LOAD_SUCCESS',
    LOAD_FAILURE: 'STATs_LOAD_FAILURE',
};
